# frontend/Dockerfile

FROM node:18

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all project files
COPY . .

# Expose React dev server port
EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]